Upgrading

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -11,7 +11,7 @@ if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
 fi
 
 # Customize to your needs...
-alias ls='ls --color=auto'
+#alias ls='ls --color=auto'
 alias ll='ls -lF'
 alias la='ls -A'
 alias l='ls -CF'
@@ -75,3 +75,61 @@ function mcd() {
 }
 
 function ssh_tmux() { ssh -t "$1" tmux a || ssh -t "$1" tmux; }
+
+[[ -f ~/.bash_profile ]] && source ~/.bash_profile
+eval "$(pyenv init -)"
+
+export PATH="$HOME/.jenv/bin:$PATH"
+eval "$(jenv init -)"
+
+# Git
+git_fwd() {
+  git checkout $(git rev-list --topo-order HEAD.."$*" | tail -1)
+}
+alias git_bwd="git checkout HEAD~"
+
+export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
+
+
+#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
+export SDKMAN_DIR="/Users/quentinl/.sdkman"
+[[ -s "/Users/quentinl/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/quentinl/.sdkman/bin/sdkman-init.sh"
+
+export PATH=$HOME/bin:$PATH
+
+mvn-or-mvnw () {
+  if [ -x ./mvnw ]
+  then
+    echo "executing mvnw instead of mvn"
+    ./mvnw "$@"
+  else
+    mvn "$@"
+  fi
+}
+alias mvn='mvn-or-mvnw'
+
+# added by travis gem
+[ -f /Users/quentinl/.travis/travis.sh ] && source /Users/quentinl/.travis/travis.sh
+
+export PIPELINE_REPO_DIR=/Users/quentinl/projects/pipeline
+
+aws_assume_role() {
+#  CREDS=$(aws sts assume-role --role-arn arn:aws:iam::042786531511:role/EngineeringAccess --role-session-name test --serial-number arn:aws:iam::071790713882:mfa/quentinl --token-code $1 --output text | grep CREDENTIALS |  tr -s ' ')
+#
+#  if [ "$?" -ne "0" ]; then
+#    echo -e "Failed while calling aws sts assume-role"
+#  else
+#    credentials=($CREDS)
+#    echo -e  "Setting temporary credentials ${credentials[1]} valid until ${credentials[2]}"
+#    export AWS_ACCESS_KEY_ID="${credentials[1]}"
+#    export AWS_SECRET_ACCESS_KEY="${credentials[3]}"
+#    export AWS_SESSION_TOKEN="${credentials[4]}"
+#  fi
+
+  aws sts assume-role --role-arn arn:aws:iam::042786531511:role/EngineeringAccess --role-session-name "DevAccount" --serial-number arn:aws:iam::071790713882:mfa/quentinl --token-code $1 | \
+  jq -r  '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "'
+
+}
+
+alias UNSET_AWS=$'source <(env | awk -F= \' /AWS/ {print "unset ", $1} \')'
+alias ecr-login='aws ecr get-login --no-include-email --region eu-west-1'
